# Generated by Django 2.2.28 on 2022-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressjlngwrhuzv'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressjlngwrhuzv',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
